### ISSUE TITLE
Move JS object/class up a whole step?

### ISSUE THREAD

**Issue by mapsam** [mapbox/mbtiles-geostats#1]
Here's what requiring and setting up this library looks like:

```javascript
var module = require('@mapbox/mbtiles-geostats');
var MBS = module.MBTilesGeostats();
mbs.addBuffer( ... );
// ...
```

Can we change this so the object returned form require is the main function?

```javascript
var MBS = require('@mapbox/mbtiles-geostats');
var mbs = new MBS();
// ...
```

@gretacb

**Comment by springmeyer** [comment]
I don't know if that is possible on the C++ side, but this is easy in JS by doing:

```diff
- module.exports = require('./binding/mbtiles_geostats.node');
+ module.exports = require('./binding/mbtiles_geostats.node').MBTilesGeostats;
```

**Comment by mapsam** [comment]
oh excellent - that's way easier. Thanks @springmeyer!

**Comment by mapsam** [comment]
Resolved in https://github.com/mapbox/mbtiles-geostats/commit/5ff69c039cd62989de7fab1eabdd349b0cbed72f
